#!/usr/bin/expect -f
set timeout 60
spawn ssh -i ssh_key.pem -o StrictHostKeyChecking=no root@strapi.wegov.nyc "find /root /home /var -name .env -maxdepth 4 2>/dev/null; echo '---PROCESSES---'; docker ps 2>/dev/null; pm2 list 2>/dev/null"
expect {
    "Enter passphrase*" {
        send "Sq;LfI)?~5O?\r"
        exp_continue
    }
    "Permission denied*" {
        puts "\nAUTHENTICATION FAILED"
        exit 1
    }
    eof
}
